package com.woowacourse.zzimkkong.domain;

import lombok.Getter;

@Getter
public enum ProfileEmoji {
    MAN_LIGHT_SKIN_TONE_TECHNOLOGIST("\uD83E\uDDD1\uD83C\uDFFB\u200D\uD83D\uDCBB"),
    MAN_MEDIUM_LIGHT_SKIN_TONE_TECHNOLOGIST("\uD83E\uDDD1\uD83C\uDFFC\u200D\uD83D\uDCBB"),
    MAN_MEDIUM_SKIN_TONE_TECHNOLOGIST("\uD83E\uDDD1\uD83C\uDFFD\u200D\uD83D\uDCBB"),
    MAN_MEDIUM_DARK_SKIN_TONE_TECHNOLOGIST("\uD83E\uDDD1\uD83C\uDFFE\u200D\uD83D\uDCBB"),
    MAN_DARK_SKIN_TONE_TECHNOLOGIST("\uD83E\uDDD1\uD83C\uDFFF\u200D\uD83D\uDCBB"),

    WOMAN_LIGHT_SKIN_TONE_TECHNOLOGIST("\uD83D\uDC69\uD83C\uDFFB\u200D\uD83D\uDCBB"),
    WOMAN_MEDIUM_LIGHT_SKIN_TONE_TECHNOLOGIST("\uD83D\uDC69\uD83C\uDFFC\u200D\uD83D\uDCBB"),
    WOMAN_MEDIUM_SKIN_TONE_TECHNOLOGIST("\uD83D\uDC69\uD83C\uDFFD\u200D\uD83D\uDCBB"),
    WOMAN_MEDIUM_DARK_SKIN_TONE_TECHNOLOGIST("\uD83D\uDC69\uD83C\uDFFE\u200D\uD83D\uDCBB"),
    WOMAN_DARK_SKIN_TONE_TECHNOLOGIST("\uD83D\uDC69\uD83C\uDFFF\u200D\uD83D\uDCBB");

    private final String code;

    ProfileEmoji(final String code) {
        this.code = code;
    }
}
