export const Z_INDEX = {
  MODAL_OVERLAY: 104,
  DRAWER_DIMMER: 102,
  DRAWER_CONTENT: 103,
  TIME_PICKER_DIMMER: 100,
  TIME_PICKER_OPTIONS: 101,
  HEADER: 99,
  SELECT_LIST_BOX_BUTTON: 50,
  SELECT_LIST_BOX: 49,
  SPACE_ADD_BUTTON: 48,
};

export const FORM_MAX_WIDTH = '660px';
