name: FE Test

on:
  pull_request:
    branches: [main, dev]

jobs:
  Check-Changed-File:
    runs-on: ubuntu-latest
    outputs:
      front-end: ${{ steps.filter.outputs.front-end }}
    steps:
      - name: check if front-end directory has changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            front-end:
              - 'front-end/**'
  FE-Test:
    needs: Check-Changed-File
    if: ${{ needs.changes.outputs.front-end == 'true' }}
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend

    strategy:
      matrix:
        node-version: [14.16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Node Version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: yarn install
        working-directory: ${{ env.working-directory }}

      - name: yarn test
        run: yarn test:ci
        working-directory: ${{ env.working-directory }}
